---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  # type: NodePort
  type: ClusterIP
  ports:
    - port: {{ include "port" . }}
      # nodePort: 30001
      targetPort: {{ include "port" . }}
      protocol: TCP
  selector:
    app: {{ .Release.Name }}
