all:
  children:
    webserver: {}
    database: {}
  vars:
    ansible_user: yc-user
    ansible_ssh_private_key_file: "{{ inventory_dir }}/../../.ssh/ansible.ed25519"
    ansible_python_interpreter: /usr/bin/python3.8

webserver:
  vars:
    nginx_version: 1.28.0
  hosts:
    webserver-testing-01:
      ansible_host: 89.169.141.254
    webserver-testing-02:
      ansible_host: 89.169.190.216
    webserver-testing-03:
      ansible_host: 158.160.144.253

database:
  vars:
    postgres_version: 16
  hosts:
    database-testing-01:
      ansible_host: 158.160.144.252
