- name: Install packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    state: present
    name:
      - nginx

- name: Ensure Nginx is enabled
  ansible.builtin.systemd:
    name: nginx
    enabled: true

- name: Copy main Nginx configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "{{ nginx_config_dest }}"
    backup: true
    owner: root
    group: root
    mode: "0644"
  notify: Restart nginx

- name: Test Nginx configuration
  ansible.builtin.command: nginx -t
  register: nginx_test
  failed_when: nginx_test.rc != 0
  changed_when: false

- name: Start Nginx service
  ansible.builtin.systemd:
    name: nginx
    state: started
